name: Build and Push Docker Image
description: |
  This action builds and pushes a Docker image to Google Artifact Registry.
  It uses Docker Buildx for building multi-platform images and Google Cloud authentication for pushing to Artifact
  Registry.
author: Reece Tech
branding:
  icon: package
  color: blue
inputs:
  project:
    description: The Google Cloud project ID.
    required: true
  project_number:
    description: The Google Cloud project number.
    required: true
  region:
    description: The Google Cloud region for Artifact Registry.
    required: true
    default: australia-southeast1
  image_name:
    description: The name of the Docker image to build.
    required: false
    default: coursebox-action
  image_tag:
    description: The tag for the Docker image.
    required: false
    default: latest # This is not used in the action, but can be used for reference or future use.
  access_token_lifetime:
    description: The lifetime of the access token in seconds.
    required: false
    default: '1300' # 21 minutes, which is the maximum allowed by Google  Cloud for workload identity federation. 
    # This is used to ensure the token does not expire during the build process.
    # If you need a longer lifetime, you can set it to 3600 (1 hour) or 7200 (2 hours), but this is not recommended
    # as it may lead to security issues. The default value is set to 1300
    # to ensure the token is valid for the duration of the build process without exceeding the maximum
    # allowed lifetime. 
    # If you need to change this value, make sure to update the access_token_lifetime input in the action
    # and the access_token_lifetime parameter in the google-github-actions/auth action.
    project:
      type: string
      required: true
    project_number:
      type: string
      required: true
outputs:
    image_tag_version:
      description: 'Image tag version'
      value: ${{ jobs.build.outputs.image_tag_version }}

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - id: auth
      name: Google Authentication
      uses: google-github-actions/auth@v0.6.0
      with:
        token_format: access_token
        workload_identity_provider: projects/${{ inputs.project_number }}/locations/global/workloadIdentityPools/github/providers/github-provider
        service_account: github@${{ inputs.project }}.iam.gserviceaccount.com
        access_token_lifetime: 1300s

    - uses: docker/login-action@v1
      name: Docker Authentication
      with:
        registry: ${{ inputs.region }}-docker.pkg.dev
        username: oauth2accesstoken
        password: "${{ steps.auth.outputs.access_token }}"

    - uses: reecetech/version-increment@2024.10.1
      name: Version Patch
      id: version
      with:
        release_branch:  ${{ github.event_name != 'pull_request' &&  github.event.repository.default_branch || github.base_ref }}
        scheme: semver
        increment: patch

    - uses: docker/metadata-action@v4
      name: Prepare docker tag
      id: image_tag
      with:
        images: ${{ github.event.repository.name }}
        flavor: |
          latest=false
        tags: |
          type=semver,priority=900,pattern={{raw}},value=${{ steps.version.outputs.v-version }},enable=${{ github.ref_name == 'main' || startsWith(github.ref, 'refs/heads/release/hotfix-') }}

  
    - uses: docker/build-push-action@v3
      name: Build And Push
      with:
        push: false # ${{ github.event_name != 'pull_request'}}
        tags: ${{ steps.image_tag.outputs.tags }}

    # - name: Build and export
    #   uses: docker/build-push-action@v6
    #   with:
    #     push: false
    #     tags: ${{ steps.image_tag.outputs.tags }}
    #     outputs: type=docker,dest=${{ github.workspace }}/${{ steps.version.outputs.v-version }}.tar ## DELETE-ME-LATER

    # - name: list tar files
    #   shell: bash
    #   run: |
    #     ls -al ${{ github.workspace }}
    

    # - name: Upload artifact
    #   # if: github.event_name != 'pull_request'
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: docker-image
    #     path: ${{ github.workspace }}/${{ steps.version.outputs.v-version }}.tar

    - name: Set env
      id: tag
      shell: bash
      run: echo "DOCKER_IMAGE_TAG=${{ fromJSON(steps.image_tag.outputs.json).labels['org.opencontainers.image.version'] }}" >> $GITHUB_OUTPUT

    - name: Job Summary
      shell: bash
      run: |
        echo "### build version : ${{ fromJSON(steps.image_tag.outputs.json).labels['org.opencontainers.image.version'] }}" >> $GITHUB_STEP_SUMMARY



